name: CFCommit

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: CFCommit
        uses: GitDaksh/CFCommit@main # <--- ESTA ES LA LÍNEA CORREGIDA
        with:
          cf_user_name: ${{ secrets.CF_USER_NAME }}
          gh_token: ${{ secrets.GH_TOKEN }}
          commit_message: "feat: ✨ Added Solution for"
